# Generated by Django 2.1.7 on 2019-03-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0002_auto_20190331_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
